// ──────────────────────────────────────────────────────────────────────────────
// Country Pack Generator
// Usage: npx tsx scripts/generate-country-packs.ts scripts/countries.csv
//
// Generates country configuration files from a CSV
// CSV columns: iso2,name,defaultLocale,locales,currency,timeZone,mapProvider
// ──────────────────────────────────────────────────────────────────────────────

import * as fs from 'fs';
import * as path from 'path';

const [, , csvPath] = process.argv;

if (!csvPath) {
  console.error('❌ Usage: npx tsx scripts/generate-country-packs.ts <countries.csv>');
  process.exit(1);
}

if (!fs.existsSync(csvPath)) {
  console.error(`❌ File not found: ${csvPath}`);
  process.exit(1);
}

// Parse CSV
const csv = fs.readFileSync(csvPath, 'utf8').trim().split(/\r?\n/);
const header = csv.shift();

if (!header) {
  console.error('❌ Empty CSV file');
  process.exit(1);
}

console.log('🌍 Generating country packs...\n');

const outDir = path.join(process.cwd(), 'src', 'countries');
const generatedCountries: string[] = [];

for (const row of csv) {
  const [iso2, name, defaultLocale, locales, currency, timeZone, mapProvider] = row
    .split(',')
    .map(s => s.trim());

  if (!iso2 || !name) continue;

  const dir = path.join(outDir, iso2);
  fs.mkdirSync(dir, { recursive: true });

  // Determine coordinate system based on map provider
  const coordSystem = mapProvider === 'amap' || mapProvider === 'baidu' ? 'GCJ-02' : 'WGS84';

  // Parse locales (comma-separated within quotes or space-separated)
  const localesArray = locales
    ? locales.split(/[;|]/).map(l => l.trim())
    : [defaultLocale, 'en-GB'];

  const template = `// ──────────────────────────────────────────────────────────────────────────────
// ${name} Country Configuration
// Auto-generated by generate-country-packs.ts
// ──────────────────────────────────────────────────────────────────────────────

import { CountryConfig } from '../types';

const ${iso2}: CountryConfig = {
  iso2: '${iso2}',
  name: '${name}',
  defaultLocale: '${defaultLocale}',
  locales: ${JSON.stringify(localesArray)},
  currency: '${currency}',
  timeZones: ['${timeZone}'],
  map: {
    provider: '${mapProvider || 'google'}',
    coordSystem: '${coordSystem}'
  },
  forms: {
    addressSchema: '${iso2}',
    dialingCountry: '${iso2}'
  },
  content: {
    emergency: {},
    quickStarts: []
  },
  features: {
    showJetLagTools: true,
    supportsEsimAdvice: ${iso2 !== 'CN'},
    mapTrafficLayer: true
  }
};

export default ${iso2};
`;

  fs.writeFileSync(path.join(dir, 'config.ts'), template, 'utf8');
  generatedCountries.push(iso2);

  console.log(`✅ Generated: ${iso2} (${name})`);
}

// Regenerate index.ts
console.log('\n📦 Updating country registry...');

const imports = generatedCountries.map(iso2 => `import ${iso2} from './${iso2}/config';`).join('\n');
const mapEntries = generatedCountries.join(', ');

const indexContent = `// ──────────────────────────────────────────────────────────────────────────────
// Country Configuration Registry
// Auto-generated by generate-country-packs.ts
// ──────────────────────────────────────────────────────────────────────────────

${imports}

export * from './types';

// Registry of all supported countries
export const COUNTRIES = {
  ${mapEntries}
} as const;

export type CountryIso2 = keyof typeof COUNTRIES;

// Helper to get country by ISO2 code with fallback
export function getCountry(iso2: string) {
  return COUNTRIES[iso2 as CountryIso2] || COUNTRIES.TH;
}

// Get list of all countries for UI
export function getAllCountries() {
  return Object.values(COUNTRIES);
}

// Get all supported locales across all countries
export function getAllLocales() {
  const locales = new Set<string>();
  Object.values(COUNTRIES).forEach(country => {
    country.locales.forEach(locale => locales.add(locale));
  });
  return Array.from(locales);
}
`;

fs.writeFileSync(path.join(outDir, 'index.ts'), indexContent, 'utf8');

console.log(`✅ Updated registry with ${generatedCountries.length} countries`);
console.log('\n🎉 Done! Country packs generated successfully.');
console.log('📝 Next steps:');
console.log('   1. Review generated configs in src/countries/');
console.log('   2. Add country-specific content (emergency numbers, transit cards, etc.)');
console.log('   3. Create address schemas in src/services/address.ts');
